name: Build, Push to Azure ACR, Gitops

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'
  release:
    types: [created]

# permissions:
#   id-token: write
#   contents: read

env:
  GITHUB_SHA: ${{ github.sha }}
  ACR_NAME: kyncjot
  GITOPS_REPO: anandDev77/stocktrader-gitops
  GITOPS_DIR: application
  IMAGE_NAME: portfolio
  APP_NAME: portfolio
  IMAGE_TAG: ${{ github.sha }}
  GITOPS_USERNAME: ${{ secrets.GITOPS_USERNAME }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Build and package app
      run: mvn clean package

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true

    - name: Azure ACR Login
      run: az acr login --name $ACR_NAME

    - name: Build and Push Docker Image to ACR
      run: |
        ACR_LOGIN_SERVER=$(az acr show --name $ACR_NAME --query loginServer --output tsv)
        docker build -t $ACR_LOGIN_SERVER/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
          --build-arg GITHUB_SHA="$GITHUB_SHA" .
        docker push $ACR_LOGIN_SERVER/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        docker tag $ACR_LOGIN_SERVER/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} $ACR_LOGIN_SERVER/${{ env.IMAGE_NAME }}:latest
        docker push $ACR_LOGIN_SERVER/${{ env.IMAGE_NAME }}:latest


#   update-gitops-repo:
#     name: Publish image updates to gitops repo
#     runs-on: ubuntu-latest
#     needs: [setup-build-publish-deploy]
#     steps:
#       - name: Checkout gitops repo
#         uses: actions/checkout@v2
#         with:
#           repository: ${{ env.GITOPS_REPO }}
#           path: gitops
#           token: ${{ secrets.GITOPS_TOKEN }}

#       - name: Update application
#         run: |
#           set -x
#           set +e
#           ls -la
#           ls -la gitops
#           cd gitops
#           echo "print yq version"
#           yq --version
#           APP_IMAGE="${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}"
#           VERSION="${{ github.sha }}"
#           APP_NAME="${{ env.APP_NAME }}"
#           yq e ".spec.portfolio.image.repository = \"$APP_IMAGE\"" -i "${GITOPS_DIR}/stocktrader-aws-eks-cr.yml"
#           yq e ".spec.portfolio.image.tag = \"$VERSION\"" -i "${GITOPS_DIR}/stocktrader-aws-eks-cr.yml"
#           cat "${GITOPS_DIR}/stocktrader-aws-eks-cr.yml"
#           if [[ $(git status -s | wc -l) -eq 0 ]]; then
#             echo "No changes"
#             exit 0
#           fi
#           git add "${GITOPS_DIR}/"
#           git config --global user.name 'GH Actions'
#           git config --global user.email 'github-actions@users.noreply.github.com'
#           git commit -am "Updates ${APP_NAME} to ${VERSION}"
#           git push https://$GITOPS_USERNAME:$GITOPS_TOKEN@github.com/$GITOPS_REPO 